# general info
custom_logo: "/Users/btf/Projects/snakemake-workflow-sars-cov2/resources/IKIM.png"
custom_logo_url: "https://www.ikim.uk-essen.de/"
custom_logo_title: "Institut für Künstliche Intelligenz in der Medizin"
show_analysis_time: True
report_header_info:
  - Authors: "Alexander Thomas, Thomas Battenfeld, Folker Meyer, Johannes Köster"
  - Project: "SARS-Cov-2 strain and variant calling pipeline"
  - Contact E-mail: "to.decide@uk-essen.de"

# order of report
module_order:
  - fastqc:
      name: "Reads Quality Control"
      target: "FastQC"
  - fastp:
      name: "Reads Preprocessing"
      target: "fastp"
  - kraken:
      name: "Species Diversity (raw)"
      target: "Kraken2"
      anchor: "kraken_raw"
      path_filters:
        - "*.uncleaned.kreport2"
  - kraken:
      name: "Species Diversity (cleaned)"
      anchor: "kraken_cleaned"
      target: "Kraken2"
      info: "Kraken2 results AFTER removal of human contamination."
      path_filters:
        - "*.cleaned.kreport2"
  - kallisto:
      name: Reads Pseudoalignment
      target: Kallisto
      info: "is a program for quantifying abundances of transcripts from RNA-Seq data. It aligns the cleaned reads agains the covid reference genome."
  - quast:
      name: "Contigs (assembly)"
      anchor: "quast_assembly"
      path_filters:
        - "*/quast/unpolished/*/report.tsv"
  - picard:
      name: Duplication (raGOO)
      info: "is used to mark duplicates of the raGOO outout against the covid reference genome."
      target: "Picard"
  - samtools:
      name: "Samtools (?)"
  - quast:
      name: "Contigs (polished)"
      anchor: "quast_consensus"
      path_filters:
        - "*/quast/polished/*/report.tsv"

# sample name cleaning
fn_clean_exts:
  - ".kreport2"
  - ".contigs"
  - ".fastp"
  - ".trimmed"
  - ".fastq"
  - ".gz"
  - ".bam"
  - ".flagstat"
  - ".uncleaned"
  - ".cleaned"
  - "_L001_R1_001"
  - "_L001_R2_001"
  - "_S"
  - ".1"

# customising general Statistics
table_columns_visible:
  samtools-flagstat: False
  Samtools: False
  samtools: False
  Reads Quality Control:
    percent_duplicates: False
    percent_gc: False
    avg_sequence_length:
    percent_fails: False
    total_sequences: True
  Reads Preprocessing:
    pct_duplication: False
    after_filtering_q30_rate: False
    after_filtering_q30_bases: False
    after_filtering_gc_content: False
    total_sequencpct_survivinges: False
    pct_surviving: True
    pct_adapter: False
  Species Diversity (raw):
    "% Severe acute respiratory syndrome-related coronavirus": False
    "% Top 5": False
    "% Unclassified": False
  Species Diversity (cleaned):
    "% Severe acute respiratory syndrome-related coronavirus": False
    "% Top 5": False
    "% Unclassified": False
  Contigs (assembly):
    N50: True
    Total length: False
    Largest contig: False
  Samtools (?):
    flagstat_total: False
    mapped_passed: False
  Contigs (consensus):
    N50: True
    Total length: False
    Largest contig: False
    Genome fraction (%): False
  Duplication (raGOO):
    PERCENT_DUPLICATION: False
  Reads Pseudoalignment:
    fragment_length: False
    percent_aligned: False
    pseudoaligned_reads: False

# number formatting
read_count_multiplier: 0.001
read_count_prefix: "K"
read_count_desc: "thousands"

base_count_multiplier: 0.001
base_count_prefix: "K"
base_count_desc: "thousands"

long_read_count_multiplier: 0.001
long_read_count_prefix: "K"
long_read_count_desc: "thousands"
