#path for lineages to be simulated
lineages: config/lineages.tsv

#simulate reads 
simulation: True

#samples
number_of_samples: 3
#samples: config/samples.tsv

#number of total reads in the sample
n_reads: 50000

##tool configurations
#art simulation
f_coverage: 50
