## working mode of the workflow, the sample sheet of the uncovar workflow needs to be filled in according to the two options selected below.
## if both are false, then it will analyze the samples in the sample sheet.
# simulate reads to imitate pandemics. sample names start with 'SimulatedSample{num}-{coverage}' and num starting from 1 to {number_of_samples}. coverages
simulate_pandemics: False
number_of_samples: 3

# option for simulating given fractions for a sample in lineages.tsv. Sample name starts with 'SampleExample-{coverage}'
simulate_given: True
coverage_simulate_given: 100x

#number of total reads in the sample, considering 150 bp reads, sarscov2 has 29900 bp
n_reads_100x: 20000 #for 100x
n_reads_1000x: 200000 #for 1000x

#path for lineages to be simulated
lineages_and_fractions: config/lineages.tsv

# if both simulation options are False, then sample sheet will be used.
samples: config/samples_wastewater_test_1.tsv

#NCBI accession ID for the reference genome sequence
#for hiv NC_001802.1
reference_accession: NC_045512 

#lineages path:
#for hiv
# lineages: resources/lineages/hiv_5_virus_mix.fasta
#for sarscov2
viral_lineages_fasta: resources/lineages/pango-consensus-sequences_genome-nuc.fasta

##tool configurations
#art simulation
f_coverage: 50

#threads for tools
bwa_threads: 1
kallisto_index_threads: 1
kallisto_quant_threads: 1

## define config of uncovar pipeline##

pepfile: config/pep/config_filled.yaml
mode: patient
virus-reference-genome:
  - NC_045512.2
human-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.fna.gz
sending_lab_number: 10259
data-handling:
  use-data-handling: true
  archive-data: true
  incoming: ../incoming/
  data: data/
  archive: ../archive/
quality-criteria:
  illumina:
    min-length-reads: 30
    min-PHRED: 20
  ont:
    min-length-reads: 200
    min-PHRED: 10
  min-identity: 0.9
  max-n: 0.05
  min-depth-with-PCR-duplicates: 20
  min-depth-without-PCR-duplicates: 10
  min-allele: 0.9
preprocessing:
  kit-adapters: --adapter_sequence GCGAATTTCGACGATCGTTGCATTAACTCGCGAA --adapter_sequence_r2
    AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  artic-primer-version: 3
  amplicon-primers: resources/nCoV-2019.primer.bed
  amplicon-reference: MN908947
assembly:
  illumina:
    shotgun: megahit-std
    amplicon: megahit-std
  oxford nanopore:
    shotgun: megahit-std
    amplicon: megahit-std
    medaka_model: r941_min_fast_g303
  ion torrent:
    shotgun: megahit-std
    amplicon: megahit-std
  min-variant-prob: 0.95
variant-calling:
  annotations:
    - orf
    - protein
  fdr: 0.05
  max-read-depth: 2000
  report:
    max-read-depth: 100
  filters:
    low-impact: ANN["IMPACT"] in ["LOW", "MODIFIER"]
    high+moderate-impact: ANN["IMPACT"] in ["HIGH", "MODERATE"]
strain-calling:
  min-fraction: 0.02
  extracted-strain-genomes: resources/genomes
  use-gisaid: false
  lineage-references:
    B.1.1.7: MZ773928
    B.1.351: MZ433432
    P.1: MZ477759
    B.1.617.2: OK091006
mth:
  S:
    - L18F
    - T19R
    - T20N
    - P26S
    - H69_V70del
    - D80A
    - D138Y
    - Y144del
    - F157_R158del
    - R190S
    - D215G
    - R246I
    - K417N
    - K417T
    - L452R
    - E484K
    - T478K
    - N501Y
    - A570D
    - D614G
    - H655Y
    - P681R
    - P681H
    - A701V
    - T716I
    - D950N
    - S982A
    - T1027I
    - D1118H
    - V1176F
non_cov2_genomes:
  - NC_005831
  - NC_002645
  - NC_006213
  - NC_006577
  - NC_019843
  - NC_004718
mixtures:
  max_reads: 294459
  no_mixtures: 500
  no_strains: 2
  use_predefined_mixtures: false
  predefined_mixtures:
    - _MIX_B-1-1-7_PERC_50_MIX_B-1-351_PERC_50
    - _MIX_B-1-1-7_PERC_90_MIX_B-1-351_PERC_10
read_lineage_call:
  number_of_samples: 100
  number_of_reads:
    - 100
    - 200
    - 300
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 3000
    - 5000
    - 7000
    - 10000
    - 30000
    - 60000
    - 120000
    - 500000
    - 1000000
  length_of_reads:
    - 100
    - 150
    - 250
assemblers_for_comparison:
  - megahit-std
  - megahit-meta-large
  - megahit-meta-sensitive
  - trinity
  - velvet
  - metaspades
  - coronaspades
  - spades
  - rnaviralspades
assemblers_used:
  shotgun: megahit-std
  amplicon: metaspades
orf_names:
  - ORF1ab
  - S
  - ORF3a
  - E
  - M
  - ORF6
  - ORF7a
  - ORF7b
  - ORF8
  - N
  - ORF10
  - 3UTR
